import Papa from "papaparse";

import type {
  BaselineDiffItem,
  BaselineDiffResult,
  FindingCluster,
  OutputFormat,
} from "../model.js";
import { clusterDisposition } from "../model.js";
import { describeScanSetChange } from "../compare.js";
import { exportBaselineHtml } from "./html.js";
import { coverageMarkdownLines } from "./markdown.js";

export function exportBaselineDiff(result: BaselineDiffResult, format: OutputFormat): string {
  switch (format) {
    case "json":
      return `${JSON.stringify(result, null, 2)}\n`;
    case "sarif":
      return exportDiffSarif(result);
    case "csv":
      return exportDiffCsv(result);
    case "markdown":
      return exportDiffMarkdown(result);
    case "html":
      return exportBaselineHtml(result);
  }
}

function exportDiffCsv(result: BaselineDiffResult): string {
  const scanSetMessage = result.scanSetChange.detected
    ? describeScanSetChange(result.scanSetChange)
    : "";
  const rows = result.items.map((item) => ({
    scan_set_changed: result.scanSetChange.detected,
    scan_set_change: scanSetMessage,
    baseline_state: item.state,
    changed_fields: item.changedFields.join(";"),
    cluster_id: item.cluster.id,
    baseline_cluster_id: item.baselineCluster?.id ?? "",
    severity: item.cluster.severity,
    kind: item.cluster.primary.kind,
    title: item.cluster.primary.title,
    identifiers: item.cluster.identifiers.map((identifier) => identifier.value).join(";"),
    component: item.cluster.primary.component?.purl ?? item.cluster.primary.component?.name ?? "",
    assets: item.cluster.assets.map((asset) => asset.name).join(";"),
    source_tools: item.cluster.sourceTools.join(";"),
    source_records: item.cluster.members.length,
    disposition: clusterDisposition(item.cluster),
    suppressed: item.cluster.suppressed,
    non_finding: item.cluster.nonFinding,
  }));
  return `${Papa.unparse(rows, { newline: "\n", escapeFormulae: true })}\n`;
}

function exportDiffMarkdown(result: BaselineDiffResult): string {
  const lines = [
    "# VulnFuse baseline comparison",
    "",
    `> Compared ${result.summary.currentClusters} current clusters with ${result.summary.baselineClusters} baseline clusters: **${result.summary.new} new**, **${result.summary.updated} updated**, **${result.summary.absent} absent**, and ${result.summary.unchanged} unchanged.`,
    "",
    ...(result.scanSetChange.detected
      ? [`> **Warning:** ${escapeMarkdown(describeScanSetChange(result.scanSetChange))}`, ""]
      : []),
    "| State | Clusters |",
    "| --- | ---: |",
    `| New | ${result.summary.new} |`,
    `| Updated | ${result.summary.updated} |`,
    `| Absent | ${result.summary.absent} |`,
    `| Unchanged | ${result.summary.unchanged} |`,
    "",
    ...coverageMarkdownLines(result.currentSummary.coverage, "Current-run scanner coverage"),
    "## Changes",
    "",
  ];
  const changes = result.items.filter((item) => item.state !== "unchanged");
  if (changes.length === 0) lines.push("No changes from the baseline.", "");
  for (const item of changes) lines.push(...diffItemMarkdown(item));
  lines.push(
    "---",
    "",
    `Generated by VulnFuse with threshold ${result.options.threshold} and scope \`${result.options.scope}\`.`,
    "",
  );
  return lines.join("\n");
}

function diffItemMarkdown(item: BaselineDiffItem): string[] {
  const identifiers =
    item.cluster.identifiers.map((identifier) => identifier.value).join(", ") || "none";
  const component =
    item.cluster.primary.component?.purl ?? item.cluster.primary.component?.name ?? "unknown";
  return [
    `### [${item.state.toUpperCase()}] ${escapeMarkdown(item.cluster.primary.title)}`,
    "",
    `- **Severity:** ${item.cluster.severity}`,
    `- **Disposition:** ${dispositionLabel(item.cluster)}`,
    `- **Cluster:** ${inlineCode(item.cluster.id)}`,
    ...(item.baselineCluster && item.baselineCluster.id !== item.cluster.id
      ? [`- **Baseline cluster:** ${inlineCode(item.baselineCluster.id)}`]
      : []),
    `- **Identifiers:** ${escapeMarkdown(identifiers)}`,
    `- **Component:** ${inlineCode(component)}`,
    `- **Sources:** ${item.cluster.sourceTools.map(escapeMarkdown).join(", ")}`,
    ...(item.changedFields.length > 0
      ? [`- **Changed fields:** ${item.changedFields.map(escapeMarkdown).join(", ")}`]
      : []),
    ...(item.explanation
      ? [
          `- **Baseline match:** ${item.explanation.score}/100 (${item.explanation.reasons
            .map((reason) => escapeMarkdown(reason.message))
            .join("; ")})`,
        ]
      : []),
    "",
  ];
}

function exportDiffSarif(result: BaselineDiffResult): string {
  const emittedItems = result.items.filter((item) => !item.cluster.nonFinding);
  const clusters = uniqueClusters(emittedItems.map((item) => item.cluster));
  const nonFindingItems = result.items.filter((item) => item.cluster.nonFinding);
  const document = {
    $schema: "https://json.schemastore.org/sarif-2.1.0.json",
    version: "2.1.0",
    runs: [
      {
        tool: {
          driver: {
            name: "VulnFuse",
            semanticVersion: "0.4.11",
            informationUri: "https://github.com/CAOShurong/vulnfuse",
            rules: clusters.map(ruleFor),
          },
        },
        invocations: [
          {
            executionSuccessful: true,
            properties: {
              baselineComparison: result.summary,
              scanSetChange: result.scanSetChange,
              correlationOptions: result.options,
            },
          },
        ],
        results: emittedItems.map(diffResultFor),
        properties: {
          nonFindingItems,
          nonFindingExportNote:
            "Retained here instead of results[] because GitHub code scanning does not document result.kind in its supported SARIF subset.",
        },
      },
    ],
  };
  return `${JSON.stringify(document, null, 2)}\n`;
}

function ruleFor(cluster: FindingCluster): Record<string, unknown> {
  return {
    id: cluster.id,
    name: cluster.identifiers[0]?.value ?? cluster.id,
    shortDescription: { text: cluster.primary.title },
    ...(cluster.primary.description
      ? { fullDescription: { text: cluster.primary.description } }
      : {}),
    ...(cluster.primary.references[0] ? { helpUri: cluster.primary.references[0] } : {}),
    properties: {
      tags: [
        "security",
        cluster.primary.kind,
        ...cluster.identifiers.map((identifier) => identifier.value),
      ],
      "security-severity": securityScore(cluster.severity),
    },
  };
}

function diffResultFor(item: BaselineDiffItem): Record<string, unknown> {
  const cluster = item.cluster;
  const location = cluster.primary.location;
  const stableIdentity = item.baselineCluster?.id ?? cluster.id;
  const suppressions = cluster.suppressed ? sarifSuppressions(cluster) : [];
  return {
    ruleId: cluster.id,
    level: sarifLevel(cluster.severity),
    baselineState: item.state,
    message: {
      text: `${cluster.primary.title} (${item.state}; ${cluster.members.length} source record${cluster.members.length === 1 ? "" : "s"}: ${cluster.sourceTools.join(", ")})`,
    },
    fingerprints: { vulnfuseClusterId: stableIdentity },
    partialFingerprints: { primaryLocationLineHash: stableIdentity },
    ...(suppressions.length > 0 ? { suppressions } : {}),
    ...(location?.uri ? { locations: [sarifLocation(location)] } : {}),
    properties: {
      baselineState: item.state,
      changedFields: item.changedFields,
      sourceTools: cluster.sourceTools,
      sourceFindingIds: cluster.members.map((member) => member.id),
      suppressed: cluster.suppressed,
      nonFinding: cluster.nonFinding,
      suppressionEvidence: suppressionEvidence(cluster),
      matchConfidence: item.explanation?.confidence ?? "none",
      identifiers: cluster.identifiers,
      assets: cluster.assets,
      ...(item.baselineCluster ? { baselineClusterId: item.baselineCluster.id } : {}),
    },
  };
}

function dispositionLabel(cluster: FindingCluster): string {
  const disposition = clusterDisposition(cluster);
  if (disposition === "non-finding") return "non-finding evidence";
  if (disposition === "suppressed") return "effectively suppressed";
  return "active";
}

function sarifSuppressions(cluster: FindingCluster): Array<Record<string, string>> {
  const values = cluster.members.flatMap((member) => member.suppressions ?? []);
  const unique = new Map<string, Record<string, string>>();
  for (const suppression of values) {
    const value = {
      kind: suppression.kind,
      ...(suppression.status ? { status: suppression.status } : {}),
      ...(suppression.justification ? { justification: suppression.justification } : {}),
    };
    unique.set(JSON.stringify(value), value);
  }
  return [...unique.values()];
}

function suppressionEvidence(cluster: FindingCluster) {
  return cluster.members
    .filter((member) => (member.suppressions?.length ?? 0) > 0)
    .map((member) => ({
      sourceFindingId: member.id,
      sourceTool: member.source.tool,
      suppressed: member.suppressed === true,
      suppressions: member.suppressions,
    }));
}

function sarifLocation(location: NonNullable<FindingCluster["primary"]["location"]>) {
  return {
    physicalLocation: {
      artifactLocation: { uri: location.uri },
      ...(location.startLine
        ? {
            region: {
              startLine: location.startLine,
              ...(location.endLine ? { endLine: location.endLine } : {}),
              ...(location.startColumn ? { startColumn: location.startColumn } : {}),
            },
          }
        : {}),
    },
  };
}

function uniqueClusters(clusters: FindingCluster[]): FindingCluster[] {
  return [...new Map(clusters.map((cluster) => [cluster.id, cluster])).values()];
}

function sarifLevel(severity: FindingCluster["severity"]): "error" | "warning" | "note" | "none" {
  if (severity === "critical" || severity === "high") return "error";
  if (severity === "medium") return "warning";
  if (severity === "low" || severity === "info") return "note";
  return "none";
}

function securityScore(severity: FindingCluster["severity"]): string {
  return { critical: "9.5", high: "8.0", medium: "5.5", low: "2.0", info: "0.1", unknown: "0.0" }[
    severity
  ];
}

function escapeMarkdown(value: string): string {
  return value.replace(/([\\`*_{}[\]()<>#+.!|])/g, "\\$1");
}

function inlineCode(value: string): string {
  const longestRun = Math.max(0, ...(value.match(/`+/g) ?? []).map((run) => run.length));
  const delimiter = "`".repeat(longestRun + 1);
  const needsPadding = /^[ `]|[ `]$/.test(value);
  return `${delimiter}${needsPadding ? " " : ""}${value}${needsPadding ? " " : ""}${delimiter}`;
}
