import type { CorrelationResult, CoverageSummary, FindingCluster } from "../model.js";

export function exportMarkdown(result: CorrelationResult): string {
  const lines = [
    "# VulnFuse correlation report",
    "",
    `> ${result.summary.inputFindings} source findings became ${result.summary.clusters} explainable clusters; ${result.summary.duplicatesCollapsed} duplicate records were collapsed.`,
    "",
    "| Severity | Clusters |",
    "| --- | ---: |",
    ...["critical", "high", "medium", "low", "info", "unknown"].map(
      (severity) =>
        `| ${severity} | ${result.summary.bySeverity[severity as keyof typeof result.summary.bySeverity]} |`,
    ),
    "",
    ...coverageMarkdownLines(result.summary.coverage),
    "## Findings",
    "",
  ];
  for (const cluster of result.clusters) lines.push(...clusterMarkdown(cluster));
  lines.push(
    "---",
    "",
    `Generated by VulnFuse with threshold ${result.options.threshold}, scope \`${result.options.scope}\`, and line window ${result.options.lineWindow}.`,
    "",
  );
  return lines.join("\n");
}

export function coverageMarkdownLines(
  coverage: CoverageSummary,
  heading = "Scanner coverage",
): string[] {
  return [
    `## ${heading}`,
    "",
    `> ${coverage.singleToolClusters} clusters were reported by one tool and ${coverage.multiToolClusters} by multiple tools. Tool agreement is evidence coverage, not a correctness vote.`,
    "",
    "| Tool | Reports | Source findings | Clusters | Only this tool | Shared |",
    "| --- | ---: | ---: | ---: | ---: | ---: |",
    ...coverage.tools.map(
      (tool) =>
        `| ${escapeMarkdown(tool.tool)} | ${tool.reports} | ${tool.sourceFindings} | ${tool.clusters} | ${tool.exclusiveClusters} | ${tool.sharedClusters} |`,
    ),
    "",
    ...(coverage.pairwiseOmitted
      ? ["_Pairwise overlap is omitted when more than 20 tools are present._", ""]
      : coverage.pairs.length > 0
        ? [
            "### Pairwise overlap",
            "",
            "| Tool pair | Shared clusters | Union clusters | Jaccard overlap |",
            "| --- | ---: | ---: | ---: |",
            ...coverage.pairs.map(
              (pair) =>
                `| ${escapeMarkdown(pair.leftTool)} / ${escapeMarkdown(pair.rightTool)} | ${pair.sharedClusters} | ${pair.unionClusters} | ${formatPercent(pair.overlapRatio)} |`,
            ),
            "",
          ]
        : []),
  ];
}

function formatPercent(ratio: number): string {
  return `${(ratio * 100).toFixed(1)}%`;
}

function clusterMarkdown(cluster: FindingCluster): string[] {
  const identifiers =
    cluster.identifiers.map((identifier) => identifier.value).join(", ") || "none";
  const component =
    cluster.primary.component?.purl ??
    ([cluster.primary.component?.name, cluster.primary.component?.version]
      .filter(Boolean)
      .join("@") ||
      "unknown");
  const assets = cluster.assets.map((item) => item.name).join(", ") || "unknown";
  const reasons = cluster.edges
    .flatMap((edge) =>
      edge.explanation.reasons.map((reason) => `${reason.message} (+${reason.score})`),
    )
    .filter((value, index, all) => all.indexOf(value) === index);
  return [
    `### ${escapeMarkdown(cluster.primary.title)}`,
    "",
    `- **Cluster:** \`${cluster.id}\``,
    `- **Severity:** ${cluster.severity}`,
    `- **Identifiers:** ${escapeMarkdown(identifiers)}`,
    `- **Component:** ${inlineCode(component)}`,
    `- **Assets:** ${escapeMarkdown(assets)}`,
    `- **Sources:** ${cluster.sourceTools.join(", ")} (${cluster.members.length} record${cluster.members.length === 1 ? "" : "s"})`,
    `- **Match confidence:** ${cluster.confidence}`,
    ...(reasons.length > 0 ? [`- **Why merged:** ${reasons.map(escapeMarkdown).join("; ")}`] : []),
    ...(cluster.primary.remediation?.fixedVersion
      ? [`- **Fixed version:** ${escapeMarkdown(cluster.primary.remediation.fixedVersion)}`]
      : []),
    "",
  ];
}

function escapeMarkdown(value: string): string {
  return value.replace(/([\\`*_{}[\]()<>#+.!|])/g, "\\$1");
}

function inlineCode(value: string): string {
  const longestRun = Math.max(0, ...(value.match(/`+/g) ?? []).map((run) => run.length));
  const delimiter = "`".repeat(longestRun + 1);
  const needsPadding = /^[ `]|[ `]$/.test(value);
  return `${delimiter}${needsPadding ? " " : ""}${value}${needsPadding ? " " : ""}${delimiter}`;
}
